name: Deploy Backend to Railway

on:
  push:
    branches:
      - phase-3/ishika-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 🛠 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy via Railway CLI
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
